### ISSUE TITLE
[Frontend] Litera "ê" zamiast "ę" w tekście

### ISSUE THREAD

**Issue by PiotrSzafranEDU** [MaxKolac/zpi#11]
Po włączeniu aplikacji, w prawym dolnym rogu zamiast słowa "Nast**ę**pna" pojawia się słowo "Nast**ê**pna"

![image_2023-11-27_135712816](https://github.com/MaxKolac/zpi/assets/115222885/38c4be0a-4ec6-44c6-84a7-0088b0240528)

**Comment by Dudi512** [comment]
![obraz](https://github.com/MaxKolac/zpi/assets/114996168/5bc4652f-4592-474f-a227-4124fe4ec639)
