### ISSUE TITLE
[Frontend] Brak obrysu polanki do grillowania na mapie

### ISSUE THREAD

**Issue by PiotrSzafranEDU** [MaxKolac/zpi#12]
1. Włącz aplikacje
2. Kliknij przycisk "Przełącz widok"

Obszar oznaczony jako "POL" nie ma obrysu jak pozostałe obszary na mapie.
![image](https://github.com/MaxKolac/zpi/assets/115222885/ca13fff0-3280-486f-bc28-b9590706c30b)

**Comment by Dudi512** [comment]
Done >:[
![Kabacki_Segment](https://github.com/MaxKolac/zpi/assets/114996168/f0a5361e-ba7b-4172-b3de-65d9b221fa69)
