### ISSUE TITLE
[Frontend] Widoczny flickering przy przełączaniu widoku

### ISSUE THREAD

**Issue by PiotrSzafranEDU** [MaxKolac/zpi#13]
1. Włącz aplikację
2. Kliknij przycisk "Przełącz widok"

Na części ekranu gdzie ładuje się mapka jest widoczny flickering. Przy przełączaniu widoku na listę, flickering nie występuje.
Wideo w zipie.
[flickering.zip](https://github.com/MaxKolac/zpi/files/13474552/flickering.zip)

**Comment by Dudi512** [comment]
Done
