### ISSUE TITLE
[Frontend] Niepotrzebna kropka po słowie "temu" w polu "Ostatnia aktualizacja"

### ISSUE THREAD

**Issue by PiotrSzafranEDU** [MaxKolac/zpi#16]
1. Wybierz czujnik np. Czujnik 1
2. Zwróć uwagę na prawą część ekranu, sekcja "Ostatnia aktualizacja"

W innych polach czujnika żadna informacja nie kończy się kropką, więc nie ma konsystencji.

**Comment by Dudi512** [comment]
Done
![obraz](https://github.com/MaxKolac/zpi/assets/114996168/5d67e442-9cf6-420c-83ba-c2b6b9d704b4)
